apiVersion: v1
kind: Secret
metadata:
  name: nodra-secrets
  namespace: nodra-system
type: Opaque
stringData:
  admin-token: replace-me
  admin-user: admin
  admin-password: replace-me
  enrollment-token: replace-me
  agent-local-token: replace-me-too
