{{- if and .Values.externalSecret .Values.externalSecret.enabled }}
{{- if not .Values.externalSecret.secretStoreRef.name }}
{{- fail "externalSecret.enabled requires externalSecret.secretStoreRef.name" }}
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nodra.fullname" . }}
  labels:
    {{- include "nodra.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "nodra.secretName" . }}
  data: {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
