{{- $secretName := printf "%s-secrets" (include "nodra.fullname" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $adminToken := .Values.secrets.adminToken -}}
{{- if not $adminToken -}}
  {{- if $existing -}}
    {{- $adminToken = index $existing.data "admin-token" | b64dec -}}
  {{- else -}}
    {{- $adminToken = randAlphaNum 48 -}}
  {{- end -}}
{{- end -}}
{{- $adminPassword := .Values.secrets.adminPassword -}}
{{- if not $adminPassword -}}
  {{- $adminPassword = $adminToken -}}
{{- end -}}
{{- $enroll := .Values.secrets.enrollmentToken -}}
{{- if not $enroll -}}
  {{- if $existing -}}
    {{- $enroll = index $existing.data "enrollment-token" | b64dec -}}
  {{- else -}}
    {{- $enroll = randAlphaNum 48 -}}
  {{- end -}}
{{- end -}}
{{- $local := .Values.agent.localToken -}}
{{- if not $local -}}
  {{- if $existing -}}
    {{- $local = index $existing.data "agent-local-token" | b64dec -}}
  {{- else -}}
    {{- $local = randAlphaNum 48 -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "nodra.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ $adminToken | quote }}
  admin-user: {{ .Values.secrets.adminUser | default "admin" | quote }}
  admin-password: {{ $adminPassword | quote }}
  viewer-token: {{ .Values.secrets.viewerToken | default "" | quote }}
  viewer-user: {{ .Values.secrets.viewerUser | default "viewer" | quote }}
  viewer-password: {{ .Values.secrets.viewerPassword | default (.Values.secrets.viewerToken | default "") | quote }}
  enrollment-token: {{ $enroll | quote }}
  agent-local-token: {{ $local | quote }}
  {{- if .Values.secrets.databaseURL }}
  database-url: {{ .Values.secrets.databaseURL | quote }}
  {{- end }}
