{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" (include "nodra.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodra.fullname" . }}-secrets
  labels:
    {{- include "nodra.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ if .Values.secrets.adminToken }}{{ .Values.secrets.adminToken | quote }}{{ else if $existing }}{{ index $existing.data "admin-token" | b64dec | quote }}{{ else }}{{ randAlphaNum 48 | quote }}{{ end }}
  enrollment-token: {{ if .Values.secrets.enrollmentToken }}{{ .Values.secrets.enrollmentToken | quote }}{{ else if $existing }}{{ index $existing.data "enrollment-token" | b64dec | quote }}{{ else }}{{ randAlphaNum 48 | quote }}{{ end }}

  agent-local-token: {{ if .Values.agent.localToken }}{{ .Values.agent.localToken | quote }}{{ else if $existing }}{{ index $existing.data "agent-local-token" | b64dec | quote }}{{ else }}{{ randAlphaNum 48 | quote }}{{ end }}
